Fixing Breakpad Crash Reporter Hotplug Script
Checking for whether the dump file exists ion the tmp folder with the
tftp is executed. This change is needed to avoid unecessary calls made
to avoid scripts for the full folder.

Change-Id: I180fdd3e68c20825ed32dc55e1479827f5258848
Signed-off-by: Sohan Madhav Bangaru <sbangaru@codeaurora.org>

diff --git a/breakpad/breakpad-wrapper/files/breakpad_crash_reporter b/breakpad/breakpad-wrapper/files/breakpad_crash_reporter
--- a/breakpad/breakpad-wrapper/files/breakpad_crash_reporter
+++ b/breakpad/breakpad-wrapper/files/breakpad_crash_reporter
@@ -27,15 +27,17 @@ if [ ! -n "$SERVER" ]; then
 	exit 0
 fi
 
-$(tftp -l $LOCAL_PATH/$1 -r $1 -p $SERVER 2>&1)
-if [ $? -eq 0 ]; then
-    printf "%s\n" "$1 collected in $SERVER" \
-                > /dev/console
+if [ -f "$LOCAL_PATH/$1" ]; then
+    $(tftp -l $LOCAL_PATH/$1 -r $1 -p $SERVER 2>&1)
+    if [ $? -eq 0 ]; then
+        printf "%s\n" "$1 collected in $SERVER" \
+                    > /dev/console
         if [ ! -d $LOCAL_PATH/$DUMP_SENT_DIR ]; then
-            mkdir -p $LOCAL_PATH/$DUMP_SENT_DIR
+             mkdir -p $LOCAL_PATH/$DUMP_SENT_DIR
         fi
-    mv $LOCAL_PATH/$1 $LOCAL_PATH/$DUMP_SENT_DIR
-else
-    printf "%s\n" "$1 collection failed in $SERVER" \
-                 > /dev/console
+             mv $LOCAL_PATH/$1 $LOCAL_PATH/$DUMP_SENT_DIR
+    else
+        printf "%s\n" "$1 collection failed in $SERVER" \
+             > /dev/console
+    fi
 fi
