wifi_fw_mount: Add 1 sec delay for mounting Wi-Fi FW partition
This change is workaround for the error we get randormly
'/dev/mtdblock27: Can't open blockdev, err: -2'.

If first time mount will fail the we will wait for 1 sec
and retry the mount once again. If second time mount will
fail then some serious problem and will print some debug
message and print cat /proc/mtd output.

whereas, the issue is not seen on the successive boots.Issue
is seen only on the NAND based boards. So the change is
applicable only for the NAND boards.

Change-Id: I6d19847275310dc473a66ae6064e65f42712c1f9
Signed-off-by: Md Sadre Alam <quic_mdalam@quicinc.com>

diff --git a/net/wireless/files/etc/init.d/wifi_fw_mount b/net/wireless/files/etc/init.d/wifi_fw_mount
--- a/net/wireless/files/etc/init.d/wifi_fw_mount
+++ b/net/wireless/files/etc/init.d/wifi_fw_mount
@@ -112,14 +112,15 @@ mount_wifi_fw (){
 		local ubi_part=$(find_mtd_part wifi_fw 2> /dev/null)
 		if [ -n "$ubi_part" ]; then
 			/bin/mount -t squashfs $ubi_part /lib/firmware/$arch/WIFI_FW > /dev/console 2>&1
-			if [ ! -f /lib/firmware/$arch/WIFI_FW/q6_fw.mdt ] && [["$arch" != "devsoc" ]]; then
+			if [ $? -ne 0 ]; then
 				echo "WIFI FW mount failed, retry after 1 sec" > /dev/console 2>&1
 				sleep 1
 				/bin/mount -t squashfs $ubi_part /lib/firmware/$arch/WIFI_FW > /dev/console 2>&1
-			elif [ ! -f /lib/firmware/$arch/WIFI_FW/q6_fw0.mdt ] && [ ! -f /lib/firmware/$arch/WIFI_FW/q6_fw1.mdt ] && [[ "$arch" == "devsoc" ]]; then
-				echo "WIFI FW mount failed, retry after 1 sec" > /dev/console 2>&1
-				sleep 1
-				/bin/mount -t squashfs $ubi_part /lib/firmware/$arch/WIFI_FW > /dev/console 2>&1
+				if [ $? -ne 0 ]; then
+					echo "CRITICAL:WIFI FW mount failed, after 1 sec retry" > /dev/console 2>&1
+					echo $(cat /proc/mtd) > /dev/console 2>&1
+					return -1
+				fi
 			fi
 		fi
 	fi
