devsoc: wifi_fw_mount: Enable fw mount script
Change-Id: I5715b069c5a02442f5178d311b777b6169e64e0b
Signed-off-by: Manikanta Mylavarapu <quic_mmanikan@quicinc.com>

diff --git a/net/wireless/files/etc/init.d/wifi_fw_mount b/net/wireless/files/etc/init.d/wifi_fw_mount
--- a/net/wireless/files/etc/init.d/wifi_fw_mount
+++ b/net/wireless/files/etc/init.d/wifi_fw_mount
@@ -72,7 +72,7 @@ mount_wifi_fw (){
 	if [ $primaryboot -eq 1 ]; then
 		part_name="0:WIFIFW_1"
 	fi
-	if [[ "$arch" == "IPQ6018" ]] || [[ "$arch" == "IPQ5018" ]] || [[ "$arch" == "IPQ9574" ]]; then
+	if [[ "$arch" == "IPQ6018" ]] || [[ "$arch" == "IPQ5018" ]] || [[ "$arch" == "IPQ9574" ]] || [[ "$arch" == "devsoc" ]]; then
 		wifi_on_rootfs="1"
 	fi
 
@@ -91,7 +91,11 @@ mount_wifi_fw (){
 	mkdir -p /lib/firmware/$arch/WIFI_FW
 	if [ -n "$emmc_part" ]; then
 		/bin/mount -t squashfs $emmc_part /lib/firmware/$arch/WIFI_FW > /dev/console 2>&1
-		[ -f /rom/lib/firmware/$arch/WIFI_FW/q6_fw.mdt ] && cp /rom/lib/firmware/$arch/WIFI_FW/*.* /lib/firmware/$arch/WIFI_FW/
+		if [[ "$arch" == "devsoc" ]]; then
+			[ -f /rom/lib/firmware/$arch/WIFI_FW/q6_fw0.mdt ] && [ -f /rom/lib/firmware/$arch/WIFI_FW/q6_fw1.mdt ] && cp /rom/lib/firmware/$arch/WIFI_FW/*.* /lib/firmware/$arch/WIFI_FW/
+		else
+			[ -f /rom/lib/firmware/$arch/WIFI_FW/q6_fw.mdt ] && cp /rom/lib/firmware/$arch/WIFI_FW/*.* /lib/firmware/$arch/WIFI_FW/
+		fi
 	elif [ -n "$nor_flash" ]; then
 		local nor_mtd_part=$(find_mtd_part $part_name 2> /dev/null)
 		if [ -n "$nor_mtd_part" ]; then
@@ -108,14 +112,18 @@ mount_wifi_fw (){
 		local ubi_part=$(find_mtd_part wifi_fw 2> /dev/null)
 		if [ -n "$ubi_part" ]; then
 			/bin/mount -t squashfs $ubi_part /lib/firmware/$arch/WIFI_FW > /dev/console 2>&1
-			if [ ! -f /lib/firmware/$arch/WIFI_FW/q6_fw.mdt ]; then
+			if [ ! -f /lib/firmware/$arch/WIFI_FW/q6_fw.mdt ] && [["$arch" != "devsoc" ]]; then
+				echo "WIFI FW mount failed, retry after 1 sec" > /dev/console 2>&1
+				sleep 1
+				/bin/mount -t squashfs $ubi_part /lib/firmware/$arch/WIFI_FW > /dev/console 2>&1
+			elif [ ! -f /lib/firmware/$arch/WIFI_FW/q6_fw0.mdt ] && [ ! -f /lib/firmware/$arch/WIFI_FW/q6_fw1.mdt ] && [[ "$arch" == "devsoc" ]]; then
 				echo "WIFI FW mount failed, retry after 1 sec" > /dev/console 2>&1
 				sleep 1
 				/bin/mount -t squashfs $ubi_part /lib/firmware/$arch/WIFI_FW > /dev/console 2>&1
 			fi
 		fi
 	fi
-	if [ -f /lib/firmware/$arch/WIFI_FW/q6_fw.mdt ]; then
+	if [ -f /lib/firmware/$arch/WIFI_FW/q6_fw.mdt ] || ([ -f /lib/firmware/$arch/WIFI_FW/q6_fw0.mdt ] && [ -f /lib/firmware/$arch/WIFI_FW/q6_fw1.mdt ]); then
 		echo " WIFI FW mount is successful" > /dev/console 2>&1
 	fi
 
@@ -364,7 +372,12 @@ boot() {
 		mount_bt_fw "IPQ5018"
 		mount_wifi_fw "IPQ5018"
 	else
-		echo "\nInvalid Target"
+		local emu=$(grep -o "EMULATION" /proc/device-tree/model)
+		if [ "$emu" == "EMULATION" ]; then
+			mount_wifi_fw "devsoc"
+		else
+			echo "\nInvalid Target"
+		fi
 	fi
 }
 
@@ -474,8 +487,13 @@ stop() {
 		stop_wifi_fw "IPQ5018"
 		stop_bt_fw "IPQ5018"
 	else
-		echo "\nInvalid Target"
-		return 0
+		local emu=$(grep -o "EMULATION" /proc/device-tree/model)
+		if [ "$emu" == "EMULATION" ]; then
+			stop_wifi_fw "devsoc"
+		else
+			echo "\nInvalid Target"
+			return 0
+		fi
 	fi
 	return 0
 }
