wifi_fw_mount : add wifi fw mount support for ipq54xx
This change adds wifi firmware mount support for
ipq54xx with respect to new failsafe design.

This change also enables sysupgrade-helper package
for ipq54xx target.

Change-Id: Iba50f2293da198a3f2635aa7bd375c6fd6c461a2
Signed-off-by: Vijay Balaji <quic_vijbal@quicinc.com>

diff --git a/net/wireless/files/etc/init.d/wifi_fw_mount b/net/wireless/files/etc/init.d/wifi_fw_mount
--- a/net/wireless/files/etc/init.d/wifi_fw_mount
+++ b/net/wireless/files/etc/init.d/wifi_fw_mount
@@ -46,6 +46,71 @@ caldata_symlink_creation(){
 	fi
 }
 
+get_partname() {
+	local part_name=""
+	local parse_value=4
+	local mtdpart=$(grep "\"0:BOOTCONFIG\"" /proc/mtd | awk -F: '{print $1}')
+
+	dd if=/dev/${mtdpart} of=/tmp/bootconfig.bin
+
+	dumpimage -b $parse_value &> /dev/null
+	if [[ "$?" == 1 ]];then
+		echo "Unable to read bootconfig"
+		return 1
+	fi
+
+	if [ -e /tmp/bootconfig_members.txt ]; then
+		continue
+	else
+		echo " Parsed bootconfig info not available "
+		return 1
+	fi
+
+	local boot_set=$(grep "Boot-set" /tmp/bootconfig_members.txt | awk -F: '{print $2}')
+	local image_status_A=$(grep "Image-set-status-A" /tmp/bootconfig_members.txt | awk -F: '{print $2}')
+	local image_status_B=$(grep "Image-set-status-B" /tmp/bootconfig_members.txt | awk -F: '{print $2}')
+
+	if [ "$boot_set" -eq 0 ] && [ "$image_status_A" -ne 0 ]; then
+		part_name="1"
+	elif [ "$boot_set" -eq 1 ] && [ "$image_status_B" -eq 0 ]; then
+		part_name="1"
+	fi
+
+	echo $part_name
+}
+
+get_partname_legacy() {
+	local part_name=$1
+	local age0=$(cat /proc/boot_info/bootconfig0/age)
+	local age1=$(cat /proc/boot_info/bootconfig1/age)
+	local bootname="bootconfig1"
+
+	#Try mode
+	if [ -e /proc/upgrade_info/trybit ]; then
+		if [ -e /proc/upgrade_info/trymode_inprogress ]; then
+			if [ $age0 -le $age1 ]; then
+				bootname="bootconfig0"
+			else
+				bootname="bootconfig1"
+			fi
+		else
+			if [ $age1 -ge $age0 ]; then
+				bootname="bootconfig1"
+			else
+				bootname="bootconfig0"
+			fi
+		fi
+	fi
+
+	primaryboot=$(cat /proc/boot_info/$bootname/$part_name/primaryboot)
+	if [ $primaryboot -eq 1 ]; then
+		part_name="0:WIFIFW_1"
+	fi
+
+	echo $part_name
+}
+
+
 mount_wifi_fw (){
 	local emmc_part=""
 	local nand_part=""
@@ -92,31 +157,16 @@ mount_wifi_fw (){
 	;;
 	esac
 
-	local age0=$(cat /proc/boot_info/bootconfig0/age)
-	local age1=$(cat /proc/boot_info/bootconfig1/age)
-	local bootname="bootconfig1"
-
-	#Try mode
-	if [ -e /proc/upgrade_info/trybit ]; then
-		if [ -e /proc/upgrade_info/trymode_inprogress ]; then
-			if [ $age0 -le $age1 ]; then
-				bootname="bootconfig0"
-			else
-				bootname="bootconfig1"
-			fi
-		else
-			if [ $age1 -ge $age0 ]; then
-				bootname="bootconfig1"
-			else
-				bootname="bootconfig0"
-			fi
+	if [ "$arch" == "IPQ5424" ]; then
+		local index=$(get_partname $part_name $arch)
+		if [ "$index" == "1" ]; then
+			part_name=${part_name}_${index}
+			ubi_part_name=${ubi_part_name}_${index}
 		fi
+	else
+		part_name=$(get_partname_legacy $part_name)
 	fi
 
-	primaryboot=$(cat /proc/boot_info/$bootname/$part_name/primaryboot)
-	if [ $primaryboot -eq 1 ]; then
-		part_name="0:WIFIFW_1"
-	fi
 	if [[ "$arch" == "IPQ6018" ]] || [[ "$arch" == "IPQ5018" ]] || [[ "$arch" == "IPQ9574" ]] || [[ "$arch" == "IPQ5332" ]] || [[ "$arch" == "IPQ5424" ]] || [[ "$arch" == "devsoc" ]]; then
 		wifi_on_rootfs="1"
 	fi
@@ -146,9 +196,9 @@ mount_wifi_fw (){
 		fi
 	elif [ -n "$nand_part" ]; then
                 if [ -n "$wifi_on_rootfs" ]; then
-                       local PART=$(grep -w  "rootfs" /proc/mtd | awk -F: '{print $1}')
+                       local PART=$(grep -w  "$ubi_part_name" /proc/mtd | awk -F: '{print $1}')
                 else
-                       local PART=$(grep -w  "WIFIFW" /proc/mtd | awk -F: '{print $1}')
+                       local PART=$(grep -w  "$part_name" /proc/mtd | awk -F: '{print $1}')
                 fi
 		ubiattach -p /dev/$PART
 		sync
@@ -469,7 +519,7 @@ mount_adsp_fw (){
 			/bin/mount -t squashfs $nor_mtd_part /lib/firmware/$arch/ADSP_FW > /dev/console 2>&1
 		fi
 	elif [ -n "$nand_part" ]; then
-		local PART=$(grep -w  "rootfs" /proc/mtd | awk -F: '{print $1}')
+		local PART=$(grep -w  "$ubi_part_name" /proc/mtd | awk -F: '{print $1}')
 		ubiattach -p /dev/$PART
 		sync
 		local ubi_part=$(find_mtd_part adsp_fw 2> /dev/null)
@@ -517,7 +567,7 @@ mount_bt_fw (){
 		nor_mtd_part=$(find_mtd_part $part_name 2> /dev/null)
 		/bin/mount -t squashfs $nor_mtd_part /lib/firmware/$arch/BT_FW > /dev/console 2>&1
 	elif [ -n "$nand_part" ]; then
-		PART=$(grep -w  "rootfs" /proc/mtd | awk -F: '{print $1}')
+		PART=$(grep -w  "$ubi_part_name" /proc/mtd | awk -F: '{print $1}')
 		ubiattach -p /dev/$PART
 		sync
 		ubi_part=$(find_mtd_part bt_fw 2> /dev/null)
@@ -585,23 +635,15 @@ stop_wifi_fw() {
 		wifi_on_rootfs="1"
 	fi
 
-	local age0=$(cat /proc/boot_info/bootconfig0/age)
-	local age1=$(cat /proc/boot_info/bootconfig1/age)
-	local bootname="bootconfig1"
-
-	#Try mode
-	if [ -e /proc/upgrade_info/trybit ]; then
-		if [ $age1 -ge $age0 ]; then
-			bootname="bootconfig1"
-		else
-			bootname="bootconfig0"
-		fi
-	fi
-
-	primaryboot=$(cat /proc/boot_info/$bootname/$part_name/primaryboot)
-	if [ $primaryboot -eq 1 ]; then
-		part_name="${part_name}_1"
-	fi
+	if [ "$arch" == "IPQ5424" ]; then
+                local index=$(get_partname $part_name $arch)
+                if [ "$index" == "1" ]; then
+                        part_name=${part_name}_${index}
+                        ubi_part_name=${part_name}_${index}
+                fi
+        else
+                part_name=$(get_partname_legacy $part_name)
+        fi
 
 	emmc_part=$(find_mmc_part $part_name 2> /dev/null)
 	nor_part=$(cat /proc/mtd | grep -w "WIFIFW" | awk '{print $1}' | sed 's/:$//')
